version: "3"

services:
  app:
    container_name: dev-hanami-book-shelf-app
    build: .
    command: hanami server --host=0.0.0.0
    ports:
      - 2300:2300
    # environment:
    #   - "DATABASE_HOST=db"
    #   - "DATABASE_PORT=5432"
    #   - "DATABASE_USER=postgres"
    #   - "DATABASE_PASSWORD=mysecretpassword1234"
    volumes:
      - $PWD:/app
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    container_name: dev-hanami-book-shelf-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test1234
